(custom-set-variables
 '(bar-cursor nil)
 '(case-fold-search t)
 '(column-number-mode t)
 '(current-language-environment "English")
 '(fast-lock-mode nil nil (fast-lock))
 '(font-lock-maximum-decoration t)
 '(kill-whole-line t)
; '(lazy-lock-mode t nil (lazy-lock))
 '(lazy-shot-mode nil nil (lazy-shot))
 '(line-number-mode t)
 '(mode-compile-always-save-buffer-p t)
 '(modeline-3d-p t)
 '(modeline-scrolling-method (quote scrollbar))
 '(pending-delete-mode t nil (pending-del))
 '(query-user-mail-address nil)
 '(sentence-end-double-space nil)
 '(transient-mark-mode t)
 '(user-mail-address "dmitry.m.kreslavskiy@jpmchase.com"))

(custom-set-faces
 '(default ((t (:size "12pt" :family "Courier"))) t))

(setq options-file-xemacs-version '(20 4))
(setq-default case-fold-search t)
(setq-default overwrite-mode nil)
(setq-default case-fold-search t)
(setq-default case-replace t)
(pending-delete-mode 1)
(setq-default zmacs-regions t)
(setq-default mouse-yank-at-point t)
(setq-default require-final-newline t)
(setq-default next-line-add-newlines nil)
(setq-default teach-extended-commands-p t)
(setq-default teach-extended-commands-timeout 4)
(setq-default debug-on-error nil)
(setq-default debug-on-quit nil)
(setq-default lpr-switches nil)
(setq-default ps-print-color-p t)
(setq-default ps-paper-type 'letter)
(setq-default get-frame-for-buffer-default-instance-limit nil)
(setq-default temp-buffer-show-function 'show-temp-buffer-in-current-frame)
(setq-default font-lock-auto-fontify t)
(setq-default font-lock-use-fonts '(or (mono) (grayscale)))
(setq-default font-lock-use-colors '(color))
(setq-default font-lock-maximum-decoration t)
(setq-default font-lock-maximum-size 256000)
(setq-default font-lock-mode-enable-list nil)
(setq-default font-lock-mode-disable-list nil)
(require 'paren)
(paren-set-mode 'blink-paren)
(if (featurep 'scrollbar) (progn (add-spec-list-to-specifier scrollbar-width 'nil) (add-spec-list-to-specifier scrollbar-height 'nil)))
(add-spec-list-to-specifier modeline-shadow-thickness '((global (nil . 2))))
(setq-default truncate-lines nil)
(setq-default bar-cursor 2)
(setq-default buffers-menu-max-size 25)
(setq-default complex-buffers-menu-p t)
(setq-default buffers-menu-sort-function 'sort-buffers-menu-by-mode-then-alphabetically)
(setq-default buffers-menu-grouping-function 'group-buffers-menu-by-mode-then-alphabetically)
(setq-default buffers-menu-submenus-for-groups-p nil)
(setq-default font-menu-ignore-scaled-fonts t)
(setq-default font-menu-this-frame-only-p nil)
(if (featurep 'toolbar) (progn (set-default-toolbar-position 'top) (add-spec-list-to-specifier default-toolbar-visible-p 'nil) (add-spec-list-to-specifier toolbar-buttons-captioned-p 'nil)))
(setq-default mouse-avoidance-mode nil)
(setq-default browse-url-browser-function 'browse-url-w3)
